### ISSUE TITLE
Installation last steps

### ISSUE THREAD

**Issue by totox93** [ns-4/NS4-DEV#1]

**Comment by totox93** [comment]
I tried to install your ns3 extension. I have practically used the standard python script provided by ns3 to create a new module, so that the system recognizes and adds the ns4 module to the things to be built with "./waf build" to integrate it with the simulator. 
After that, I copied the files from this repository in it and tried to build (since without building is like if the new module is not there, indeed I can't even run the examples as you suggest at the end of the installation).
The problem is that I get this error:
"Could not find a task generator for the name nse-ns4". 
Do you know if there is any solution to the problem?

**Comment by fancz2002** [comment]
This should be fixed. Please check the current version. Thanks.
